theme : jekyll-theme-minimal
markdown : kramdown
category-list :
    -
        tag : jekyll
        name_en : jekyll
        name_ko : jekyll
    -
        tag : linux
        name_en : linux
        name_ko : 리눅스
    -
        tag : html5
        name_en : HTML5
        name_ko : HTML5
